FROM python:3.7

# Django
ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE back.settings_prod
ENV APP_PATH /app

COPY . $APP_PATH/
WORKDIR $APP_PATH
RUN pip install -r requirements/prod.txt
RUN python manage.py collectstatic --noinput
